"""empty message

Revision ID: 02a6e231d01b
Revises: 7a7507646e65
Create Date: 2021-08-11 19:18:05.249238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a6e231d01b'
down_revision = '7a7507646e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'follows', 'accounts', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    # ### end Alembic commands ###
