"""empty message

Revision ID: 053c4890c80a
Revises: f4cdb18bcad8
Create Date: 2021-08-10 14:11:17.960752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053c4890c80a'
down_revision = 'f4cdb18bcad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('videos', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('likes', sa.INTEGER(), nullable=True))
    op.drop_table('like')
    # ### end Alembic commands ###
