"""empty message

Revision ID: efa8ee26e640
Revises: 2193979f81d9
Create Date: 2021-08-13 20:15:00.985246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa8ee26e640'
down_revision = '2193979f81d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'video_id')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.add_column('comments', sa.Column('video_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'comments', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'accounts', ['owner_id'], ['id'])
    # ### end Alembic commands ###
